ACTIVE_EMPLOYEE_STATUS = "ACTIVE"
ACTIVE_EMPLOYEE_BU_STATUS = "ACTIVE"
ACTIVE_ROLE_ASSIGNMENT_STATUS = "ACTIVE"
ACTIVE_COUNTRY_STATUS = "ACTIVE"

ROLE_USER = "USER"
ROLE_TS_ADMIN = "TS_ADMIN"
ROLE_TS_ADMIN_MASTER = "TS_ADMIN_MASTER"
ROLE_PROJECT_OWNER = "PROJECT_OWNER"
ROLE_PROJECT_MANAGER = "PROJECT_MANAGER"

SESSION_EMPLOYEE_ID_KEY = "ts_employee_id"
SESSION_EMAIL_KEY = "ts_validated_email"

AUDIT_ACTION_LOGIN_IDENTIFICATION = "LOGIN_IDENTIFICATION"
AUDIT_ACTION_DENY = "DENY"
