# Generated by Django 5.2.13 on 2026-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        ("reference_data", "0002_refdomain_refvalue_delete_referencevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=320)),
                ("interface_code", models.CharField(max_length=100)),
                ("direction", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("success_records", models.PositiveIntegerField(default=0)),
                ("error_records", models.PositiveIntegerField(default=0)),
                ("payload_reference", models.CharField(blank=True, max_length=255)),
                ("summary_message", models.TextField(blank=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration_jobs",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "requested_by_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_integration_jobs",
                        to="master_data.employee",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "integration_job",
                "ordering": ["-created_at", "interface_code"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationJobError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_no", models.PositiveIntegerField(blank=True, null=True)),
                ("entity_name", models.CharField(max_length=100)),
                ("external_key", models.CharField(blank=True, max_length=100)),
                ("error_code", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errors",
                        to="integrations.integrationjob",
                    ),
                ),
            ],
            options={
                "db_table": "integration_job_error",
                "ordering": ["integration_job", "id"],
            },
        ),
    ]
