# Generated by Django 5.2.13 on 2026-04-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferenceValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=64)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reference_value",
                "ordering": ["domain", "sort_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("domain", "code"),
                        name="reference_value_domain_code_uniq",
                    )
                ],
            },
        ),
    ]
