# Generated by Django 5.2.13 on 2026-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain_code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("active_flag", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ref_domain",
                "ordering": ["domain_code"],
            },
        ),
        migrations.CreateModel(
            name="RefValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value_code", models.CharField(max_length=100)),
                ("value_label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("active_flag", models.BooleanField(default=True)),
                ("system_flag", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="reference_data.refdomain",
                    ),
                ),
            ],
            options={
                "db_table": "ref_value",
                "ordering": ["domain__domain_code", "sort_order", "value_code"],
            },
        ),
        migrations.DeleteModel(
            name="ReferenceValue",
        ),
        migrations.AddConstraint(
            model_name="refvalue",
            constraint=models.UniqueConstraint(
                fields=("domain", "value_code"), name="ref_value_domain_value_code_uniq"
            ),
        ),
    ]
