# Generated by Django 5.2.13 on 2026-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reference_data", "0002_refdomain_refvalue_delete_referencevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("bu_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "business_unit",
                "ordering": ["bu_code"],
            },
        ),
        migrations.CreateModel(
            name="BusinessUnitConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("allow_employee_withdraw_flag", models.BooleanField(default=False)),
                ("count_non_billable_in_daily_limit_flag", models.BooleanField(default=False)),
                ("archive_after_years", models.PositiveSmallIntegerField(default=0)),
                ("enable_timer_flag", models.BooleanField(default=False)),
                ("enable_leave_integration_flag", models.BooleanField(default=False)),
                ("enable_copy_previous_week_flag", models.BooleanField(default=False)),
                (
                    "approval_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "business_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuration",
                        to="master_data.businessunit",
                    ),
                ),
            ],
            options={
                "db_table": "business_unit_configuration",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("client_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "parent_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_clients",
                        to="master_data.client",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "client",
                "ordering": ["business_unit__bu_code", "client_code"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("cost_center_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_centers",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "cost_center",
                "ordering": ["business_unit__bu_code", "cost_center_code"],
            },
        ),
        migrations.CreateModel(
            name="CustomAttributeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("attribute_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("active_flag", models.BooleanField(default=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_attribute_definitions",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "data_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "custom_attribute_definition",
                "ordering": ["business_unit__bu_code", "attribute_code"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("employee_code", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=320)),
                ("canonical_email", models.CharField(max_length=320, unique=True)),
                ("employment_start_date", models.DateField(blank=True, null=True)),
                ("employment_end_date", models.DateField(blank=True, null=True)),
                (
                    "manager_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_reports",
                        to="master_data.employee",
                    ),
                ),
                (
                    "primary_business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_employees",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "employee",
                "ordering": ["employee_code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBusinessUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("is_primary_flag", models.BooleanField(default=False)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_assignments",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_unit_assignments",
                        to="master_data.employee",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "employee_business_unit",
                "ordering": ["employee__employee_code", "business_unit__bu_code", "valid_from"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_assignments",
                        to="master_data.employee",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "employee_role",
                "ordering": ["employee__employee_code", "role__value_code", "valid_from"],
            },
        ),
        migrations.CreateModel(
            name="GeneralChargeCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("billable_flag", models.BooleanField(default=False)),
                ("common_code_flag", models.BooleanField(default=False)),
                ("requires_approval_flag", models.BooleanField(default=False)),
                ("description_required_flag", models.BooleanField(default=False)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="general_charge_codes",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "charge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "general_charge_code",
                "ordering": ["business_unit__bu_code", "code"],
            },
        ),
        migrations.CreateModel(
            name="InternalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("category_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_categories",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "internal_category",
                "ordering": ["business_unit__bu_code", "category_code"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("project_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("close_date", models.DateField(blank=True, null=True)),
                ("billable_flag", models.BooleanField(default=False)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="master_data.client",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="master_data.costcenter",
                    ),
                ),
                (
                    "internal_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="master_data.internalcategory",
                    ),
                ),
                (
                    "project_manager_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to="master_data.employee",
                    ),
                ),
                (
                    "project_owner_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to="master_data.employee",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "project",
                "ordering": ["business_unit__bu_code", "project_code"],
            },
        ),
        migrations.CreateModel(
            name="CustomAttributeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("mandatory_flag", models.BooleanField(default=False)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("active_flag", models.BooleanField(default=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_attribute_rules",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "custom_attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="master_data.customattributedefinition",
                    ),
                ),
                (
                    "general_charge_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_attribute_rules",
                        to="master_data.generalchargecode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_attribute_rules",
                        to="master_data.project",
                    ),
                ),
            ],
            options={
                "db_table": "custom_attribute_rule",
                "ordering": ["custom_attribute_definition", "valid_from"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("assignment_start_date", models.DateField()),
                ("assignment_end_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_assignments",
                        to="master_data.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="master_data.project",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "project_assignment",
                "ordering": [
                    "project__project_code",
                    "employee__employee_code",
                    "assignment_start_date",
                ],
            },
        ),
        migrations.CreateModel(
            name="ReminderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("rule_name", models.CharField(max_length=200)),
                ("active_flag", models.BooleanField(default=True)),
                ("schedule_expression", models.CharField(max_length=255)),
                ("recipient_scope", models.CharField(max_length=100)),
                ("template_code", models.CharField(max_length=100)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_rules",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "reminder_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "reminder_rule",
                "ordering": ["business_unit__bu_code", "rule_name"],
            },
        ),
        migrations.CreateModel(
            name="YearlyCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("calendar_year", models.PositiveIntegerField()),
                ("calendar_name", models.CharField(max_length=200)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yearly_calendars",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "yearly_calendar",
                "ordering": ["business_unit__bu_code", "calendar_year", "calendar_name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="assigned_calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_employees",
                to="master_data.yearlycalendar",
            ),
        ),
        migrations.CreateModel(
            name="CalendarSpecialDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("special_date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                (
                    "day_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "default_general_charge_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_for_special_days",
                        to="master_data.generalchargecode",
                    ),
                ),
                (
                    "yearly_calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="special_days",
                        to="master_data.yearlycalendar",
                    ),
                ),
            ],
            options={
                "db_table": "calendar_special_day",
                "ordering": ["yearly_calendar", "special_date"],
            },
        ),
        migrations.CreateModel(
            name="CalendarPeriodRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField()),
                ("monday_max_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tuesday_max_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("wednesday_max_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("thursday_max_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("friday_max_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "yearly_calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="period_rules",
                        to="master_data.yearlycalendar",
                    ),
                ),
            ],
            options={
                "db_table": "calendar_period_rule",
                "ordering": ["yearly_calendar", "effective_from"],
            },
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "client_code"), name="client_bu_client_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "cost_center_code"), name="cost_center_bu_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="customattributedefinition",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "attribute_code"),
                name="custom_attribute_definition_bu_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeebusinessunit",
            constraint=models.UniqueConstraint(
                fields=("employee", "business_unit", "valid_from"),
                name="employee_business_unit_window_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeebusinessunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_flag", True)),
                fields=("employee",),
                name="employee_business_unit_single_primary_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeerole",
            constraint=models.UniqueConstraint(
                fields=("employee", "role", "business_unit", "valid_from"),
                name="employee_role_window_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="generalchargecode",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "code"), name="general_charge_code_bu_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="internalcategory",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "category_code"),
                name="internal_category_bu_category_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "project_code"), name="project_bu_project_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectassignment",
            constraint=models.UniqueConstraint(
                fields=("project", "employee", "assignment_start_date"),
                name="project_assignment_window_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="reminderrule",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "rule_name"), name="reminder_rule_bu_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="yearlycalendar",
            constraint=models.UniqueConstraint(
                fields=("business_unit", "calendar_year", "calendar_name"),
                name="yearly_calendar_bu_year_name_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarspecialday",
            constraint=models.UniqueConstraint(
                fields=("yearly_calendar", "special_date"),
                name="calendar_special_day_calendar_date_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarperiodrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("effective_to__gte", models.F("effective_from"))),
                name="calendar_period_rule_date_order_chk",
            ),
        ),
    ]
