# Generated by Django 5.2.13 on 2026-04-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "master_data",
            "0002_remove_employeebusinessunit_employee_business_unit_single_primary_uniq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businessunitconfiguration",
            name="timesheet_cutoff_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
