# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.db import migrations, models

COUNTRY_SEED_ROWS = (
    (1, "Holding", "ACTIVE"),
    (2, "España", "ACTIVE"),
    (3, "Colombia", "ACTIVE"),
    (4, "Perú", "ACTIVE"),
    (5, "Argentina", "ACTIVE"),
    (6, "México", "INACTIVE"),
)


def _backfill_country_data(apps, schema_editor):
    RefDomain = apps.get_model("reference_data", "RefDomain")
    RefValue = apps.get_model("reference_data", "RefValue")
    Country = apps.get_model("master_data", "Country")
    BusinessUnit = apps.get_model("master_data", "BusinessUnit")
    YearlyCalendar = apps.get_model("master_data", "YearlyCalendar")
    CalendarPeriodRule = apps.get_model("master_data", "CalendarPeriodRule")
    Employee = apps.get_model("master_data", "Employee")
    Client = apps.get_model("master_data", "Client")
    InternalCategory = apps.get_model("master_data", "InternalCategory")
    CostCenter = apps.get_model("master_data", "CostCenter")
    GeneralChargeCode = apps.get_model("master_data", "GeneralChargeCode")
    Project = apps.get_model("master_data", "Project")

    country_domain, _ = RefDomain.objects.update_or_create(
        domain_code="COUNTRY_STATUS",
        defaults={
            "name": "Country Status",
            "description": "Country lifecycle status values.",
            "active_flag": True,
        },
    )
    active_status, _ = RefValue.objects.update_or_create(
        domain=country_domain,
        value_code="ACTIVE",
        defaults={
            "value_label": "Active",
            "description": "",
            "sort_order": 10,
            "active_flag": True,
            "system_flag": True,
        },
    )
    inactive_status, _ = RefValue.objects.update_or_create(
        domain=country_domain,
        value_code="INACTIVE",
        defaults={
            "value_label": "Inactive",
            "description": "",
            "sort_order": 20,
            "active_flag": True,
            "system_flag": True,
        },
    )

    status_map = {
        "ACTIVE": active_status,
        "INACTIVE": inactive_status,
    }
    for country_id, country_name, status_code in COUNTRY_SEED_ROWS:
        Country.objects.update_or_create(
            id=country_id,
            defaults={
                "country_name": country_name,
                "status": status_map[status_code],
                "created_by": "migration",
                "updated_by": "migration",
            },
        )

    holding_country = Country.objects.get(id=1)

    BusinessUnit.objects.filter(country_id__isnull=True).update(country_id=holding_country.id)

    for calendar in YearlyCalendar.objects.filter(country_id__isnull=True).select_related(
        "business_unit"
    ):
        calendar.country_id = calendar.business_unit.country_id or holding_country.id
        calendar.save(update_fields=["country"])

    for period_rule in CalendarPeriodRule.objects.filter(country_id__isnull=True).select_related(
        "yearly_calendar"
    ):
        period_rule.country_id = period_rule.yearly_calendar.country_id or holding_country.id
        period_rule.save(update_fields=["country"])

    for employee in Employee.objects.filter(country_id__isnull=True).select_related(
        "primary_business_unit"
    ):
        employee.country_id = employee.primary_business_unit.country_id or holding_country.id
        employee.save(update_fields=["country"])

    for client in Client.objects.filter(country_id__isnull=True).select_related("business_unit"):
        client.country_id = client.business_unit.country_id or holding_country.id
        client.save(update_fields=["country"])

    for category in InternalCategory.objects.filter(country_id__isnull=True).select_related(
        "business_unit"
    ):
        category.country_id = category.business_unit.country_id or holding_country.id
        category.save(update_fields=["country"])

    for cost_center in CostCenter.objects.filter(country_id__isnull=True).select_related(
        "business_unit"
    ):
        cost_center.country_id = cost_center.business_unit.country_id or holding_country.id
        cost_center.save(update_fields=["country"])

    for general_charge_code in GeneralChargeCode.objects.filter(
        country_id__isnull=True
    ).select_related("business_unit"):
        general_charge_code.country_id = (
            general_charge_code.business_unit.country_id or holding_country.id
        )
        general_charge_code.save(update_fields=["country"])

    for project in Project.objects.filter(country_id__isnull=True).select_related("business_unit"):
        project.country_id = project.business_unit.country_id or holding_country.id
        project.save(update_fields=["country"])


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0003_businessunitconfiguration_timesheet_cutoff_date"),
        ("reference_data", "0002_refdomain_refvalue_delete_referencevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("country_name", models.CharField(max_length=200, unique=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "country",
                "ordering": ["country_name"],
            },
        ),
        migrations.AddField(
            model_name="businessunit",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_units",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="yearlycalendar",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="yearly_calendars",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="calendarperiodrule",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calendar_period_rules",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="internalcategory",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internal_categories",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_centers",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="generalchargecode",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_charge_codes",
                to="master_data.country",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="master_data.country",
            ),
        ),
        migrations.RunPython(_backfill_country_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="businessunit",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_units",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="yearlycalendar",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="yearly_calendars",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="calendarperiodrule",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calendar_period_rules",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="internalcategory",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internal_categories",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_centers",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="generalchargecode",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="general_charge_codes",
                to="master_data.country",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="master_data.country",
            ),
        ),
    ]
