# Generated by Django 5.2.13 on 2026-05-11 11:17

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def assign_business_units_to_unambiguous_period_rules(apps, schema_editor):
    BusinessUnit = apps.get_model("master_data", "BusinessUnit")
    CalendarPeriodRule = apps.get_model("master_data", "CalendarPeriodRule")

    office_business_unit_counts = {
        row["office_id"]: row["bu_count"]
        for row in BusinessUnit.objects.values("office_id")
        .annotate(bu_count=Count("id"))
        .iterator()
    }
    office_default_business_unit_ids = {
        row["office_id"]: row["id"]
        for row in BusinessUnit.objects.values("office_id", "id").iterator()
        if office_business_unit_counts.get(row["office_id"]) == 1
    }
    for period_rule in CalendarPeriodRule.objects.filter(business_unit_id__isnull=True).iterator():
        business_unit_id = office_default_business_unit_ids.get(period_rule.office_id)
        if business_unit_id is None:
            continue
        period_rule.business_unit_id = business_unit_id
        period_rule.save(update_fields=["business_unit"])


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0011_office_level_yearly_calendars"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendarperiodrule",
            options={"ordering": ["yearly_calendar", "business_unit", "effective_from"]},
        ),
        migrations.AddField(
            model_name="calendarperiodrule",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calendar_period_rules",
                to="master_data.businessunit",
            ),
        ),
        migrations.RunPython(
            assign_business_units_to_unambiguous_period_rules,
            migrations.RunPython.noop,
        ),
    ]
