# Generated by Django 5.2.13 on 2026-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0013_calendarperiodrule_working_on_saturdays_flag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarperiodrule",
            name="saturday_max_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="calendarperiodrule",
            name="sunday_max_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
