# Generated by Django 5.2.13 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0015_ts_admin_full_office_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessunit",
            name="bu_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="businessunit",
            constraint=models.UniqueConstraint(
                fields=("office", "bu_code"),
                name="business_unit_office_bu_code_uniq",
            ),
        ),
    ]
