# Generated by Django 5.2.13 on 2026-05-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0017_general_charge_code_cost_center_required"),
        ("reference_data", "0002_refdomain_refvalue_delete_referencevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralChargeCodeApprovalRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("role_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="general_charge_code_approval_roles",
                        to="master_data.office",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "general_charge_code_approval_role",
                "ordering": ["office__office_name", "role_code"],
            },
        ),
        migrations.CreateModel(
            name="GeneralChargeCodeApprovalRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "approval_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_assignments",
                        to="master_data.generalchargecodeapprovalrole",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="general_charge_code_approval_role_assignments",
                        to="master_data.employee",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "general_charge_code_approval_role_assignment",
                "ordering": ["approval_role__role_code", "employee__employee_code", "valid_from"],
            },
        ),
        migrations.CreateModel(
            name="GeneralChargeCodeApproverRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                (
                    "approval_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="general_charge_code_assignments",
                        to="master_data.generalchargecodeapprovalrole",
                    ),
                ),
                (
                    "existing_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "general_charge_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approver_roles",
                        to="master_data.generalchargecode",
                    ),
                ),
            ],
            options={
                "db_table": "general_charge_code_approver_role",
                "ordering": ["general_charge_code", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="generalchargecodeapprovalrole",
            constraint=models.UniqueConstraint(
                fields=("office", "role_code"), name="gcc_approval_role_office_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="generalchargecodeapprovalroleassignment",
            constraint=models.UniqueConstraint(
                fields=("approval_role", "employee", "valid_from"),
                name="gcc_approval_role_assignment_window_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="generalchargecodeapproverrole",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("approval_role__isnull", True), ("existing_role__isnull", False)),
                    models.Q(("approval_role__isnull", False), ("existing_role__isnull", True)),
                    _connector="OR",
                ),
                name="gcc_approver_role_target_xor_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="generalchargecodeapproverrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("existing_role__isnull", False)),
                fields=("general_charge_code", "existing_role"),
                name="gcc_approver_role_existing_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="generalchargecodeapproverrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("approval_role__isnull", False)),
                fields=("general_charge_code", "approval_role"),
                name="gcc_approver_role_ad_hoc_uniq",
            ),
        ),
    ]
