# Generated by Django 5.2.13 on 2026-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0021_backfill_employee_calendar_setup"),
        ("reference_data", "0003_general_charge_code_approval_role_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="calendarperiodrule",
            index=models.Index(
                fields=["yearly_calendar", "business_unit", "effective_from", "effective_to"],
                name="cal_rule_cal_bu_window_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarperiodrule",
            index=models.Index(
                fields=["yearly_calendar", "effective_from", "effective_to"],
                name="cal_rule_cal_window_idx",
            ),
        ),
    ]
