# Generated by Django 5.2.13 on 2026-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        ("reference_data", "0002_refdomain_refvalue_delete_referencevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_timestamp", models.DateTimeField()),
                ("actor_email", models.EmailField(blank=True, max_length=320)),
                ("entity_name", models.CharField(max_length=100)),
                ("entity_id", models.BigIntegerField(blank=True, null=True)),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("reason_text", models.TextField(blank=True)),
                ("correlation_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "actor_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="master_data.employee",
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="master_data.businessunit",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-event_timestamp", "-id"],
                "indexes": [
                    models.Index(fields=["entity_name", "entity_id"], name="audit_log_entity_idx"),
                    models.Index(fields=["actor_employee"], name="audit_log_actor_idx"),
                ],
            },
        ),
    ]
