# Generated by Django 5.2.13 on 2026-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        ("reference_data", "0002_refdomain_refvalue_delete_referencevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approver_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_items",
                        to="master_data.employee",
                    ),
                ),
                (
                    "general_charge_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_items",
                        to="master_data.generalchargecode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_items",
                        to="master_data.project",
                    ),
                ),
                (
                    "scope_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "approval_item",
                "ordering": ["submission_cycle", "id"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(max_length=320)),
                ("action_timestamp", models.DateTimeField()),
                ("comment_text", models.TextField(blank=True)),
                (
                    "acted_by_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_actions",
                        to="master_data.employee",
                    ),
                ),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "approval_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="timesheets.approvalitem",
                    ),
                ),
            ],
            options={
                "db_table": "approval_action",
                "ordering": ["approval_item", "action_timestamp", "id"],
            },
        ),
        migrations.CreateModel(
            name="TimesheetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("work_date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("comment_text", models.TextField(blank=True)),
                ("billable_flag", models.BooleanField(default=False)),
                (
                    "activity_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "approval_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "general_charge_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheet_lines",
                        to="master_data.generalchargecode",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheet_lines",
                        to="master_data.project",
                    ),
                ),
            ],
            options={
                "db_table": "timesheet_line",
                "ordering": ["weekly_timesheet", "work_date", "id"],
            },
        ),
        migrations.AddField(
            model_name="approvalitem",
            name="timesheet_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_items",
                to="timesheets.timesheetline",
            ),
        ),
        migrations.CreateModel(
            name="TimesheetSubmissionCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("submission_no", models.PositiveIntegerField()),
                ("submitted_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cycle_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "outcome_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "submitted_by_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_timesheet_cycles",
                        to="master_data.employee",
                    ),
                ),
            ],
            options={
                "db_table": "timesheet_submission_cycle",
                "ordering": ["weekly_timesheet", "submission_no"],
            },
        ),
        migrations.AddField(
            model_name="approvalitem",
            name="submission_cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_items",
                to="timesheets.timesheetsubmissioncycle",
            ),
        ),
        migrations.CreateModel(
            name="WeeklyTimesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("current_submission_no", models.PositiveIntegerField(default=0)),
                ("submission_datetime", models.DateTimeField(blank=True, null=True)),
                ("final_approval_datetime", models.DateTimeField(blank=True, null=True)),
                ("comment_text", models.TextField(blank=True)),
                ("archive_eligible_date", models.DateField(blank=True, null=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_timesheets",
                        to="master_data.businessunit",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weekly_timesheets",
                        to="master_data.employee",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
            ],
            options={
                "db_table": "weekly_timesheet",
                "ordering": ["-week_start_date", "employee__employee_code"],
            },
        ),
        migrations.AddField(
            model_name="timesheetsubmissioncycle",
            name="weekly_timesheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission_cycles",
                to="timesheets.weeklytimesheet",
            ),
        ),
        migrations.AddField(
            model_name="timesheetline",
            name="weekly_timesheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="timesheets.weeklytimesheet",
            ),
        ),
        migrations.CreateModel(
            name="TimesheetLineAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(max_length=320)),
                ("updated_by", models.CharField(max_length=320)),
                ("value_text", models.TextField(blank=True)),
                (
                    "value_number",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_boolean", models.BooleanField(blank=True, null=True)),
                (
                    "custom_attribute_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line_values",
                        to="master_data.customattributedefinition",
                    ),
                ),
                (
                    "ref_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="reference_data.refvalue",
                    ),
                ),
                (
                    "timesheet_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_values",
                        to="timesheets.timesheetline",
                    ),
                ),
            ],
            options={
                "db_table": "timesheet_line_attribute_value",
                "ordering": ["timesheet_line", "custom_attribute_definition"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timesheet_line", "custom_attribute_definition"),
                        name="timesheet_line_attribute_value_line_definition_uniq",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklytimesheet",
            constraint=models.UniqueConstraint(
                fields=("employee", "week_start_date"),
                name="weekly_timesheet_employee_week_start_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklytimesheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("week_end_date__gte", models.F("week_start_date"))),
                name="weekly_timesheet_week_date_order_chk",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetsubmissioncycle",
            constraint=models.UniqueConstraint(
                fields=("weekly_timesheet", "submission_no"),
                name="timesheet_submission_cycle_sheet_submission_no_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="timesheetline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("project__isnull", False), ("general_charge_code__isnull", True)),
                    models.Q(("project__isnull", True), ("general_charge_code__isnull", False)),
                    _connector="OR",
                ),
                name="timesheet_line_charge_target_xor_chk",
            ),
        ),
    ]
