# Generated by Django 5.2.13 on 2026-04-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklytimesheet",
            name="period_lock_override_flag",
            field=models.BooleanField(default=False),
        ),
    ]
