# Generated by Django 5.2.13 on 2026-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0022_calendarperiodrule_cal_rule_cal_bu_window_idx_and_more"),
        ("reference_data", "0003_general_charge_code_approval_role_status"),
        ("timesheets", "0003_alter_approvalitem_approver_employee_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="approvalitem",
            index=models.Index(
                fields=["status", "approver_employee"], name="approval_item_status_appr_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalitem",
            index=models.Index(fields=["status", "project"], name="approval_item_status_prj_idx"),
        ),
        migrations.AddIndex(
            model_name="timesheetline",
            index=models.Index(
                fields=["weekly_timesheet", "work_date"], name="ts_line_sheet_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timesheetline",
            index=models.Index(fields=["project", "work_date"], name="ts_line_project_date_idx"),
        ),
        migrations.AddIndex(
            model_name="timesheetline",
            index=models.Index(
                fields=["general_charge_code", "work_date"], name="ts_line_gcc_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklytimesheet",
            index=models.Index(
                fields=["business_unit", "week_start_date"], name="weekly_ts_bu_week_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklytimesheet",
            index=models.Index(
                fields=["status", "week_start_date"], name="weekly_ts_status_week_idx"
            ),
        ),
    ]
